### ISSUE TITLE
There is some  problem with google sign-in

### ISSUE THREAD

**Issue by Pratikmehta1729** [GMPrakhar/Littlehelp#24]
![google_outh](https://user-images.githubusercontent.com/43946536/75246853-a03ac980-57f6-11ea-84de-2b8564115fea.png)

**Comment by GMPrakhar** [comment]
Hello Pratik,
Actually the problem was that Google Sign in was only allowed for HTTPS, so HTTP signins were not allowed. This issue is now resolved.

**Comment by Pratikmehta1729** [comment]
Thanks for your response and the explanation.
